# Generated by Django 6.0.7 on 2026-07-25 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("person", "Person (public official)"),
                            ("public_body", "Public body / government organization"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=500)),
                ("registry_scheme", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "registry_id",
                    models.CharField(blank=True, db_index=True, max_length=50, null=True),
                ),
                (
                    "company_number",
                    models.CharField(blank=True, db_index=True, max_length=20, null=True),
                ),
                ("role_description", models.CharField(blank=True, max_length=500, null=True)),
                ("properties", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "registry_scheme", "registry_id"],
                        name="graph_entit_entity__b3b5b4_idx",
                    ),
                    models.Index(fields=["company_number"], name="graph_entit_company_ed4f1f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("registry_id__isnull", False)),
                        fields=("registry_scheme", "registry_id"),
                        name="unique_registry_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "edge_type",
                    models.CharField(
                        choices=[
                            ("donation", "Political donation"),
                            ("officer_of", "Officer / director of company"),
                            ("referred_to_lane", "Referred supplier to VIP lane"),
                            ("declared_interest", "Declared financial interest"),
                            ("supplier_of", "Supplier of public contract"),
                            ("associate_of", "Professional or personal association"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "source_name",
                    models.CharField(
                        help_text="Electoral Commission, Parliament Register, Companies House, DHSC, etc.",
                        max_length=200,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="Source-native ID (e.g. EC donation ref, Parliament interest ID)",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("match_confidence", models.FloatField(default=1.0)),
                ("match_method", models.CharField(default="identifier", max_length=30)),
                ("amount_cents", models.BigIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                ("properties", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="graph.entity",
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="graph.entity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["edge_type", "valid_from"], name="graph_edge_edge_ty_302264_idx"
                    ),
                    models.Index(
                        fields=["source_entity", "target_entity", "edge_type"],
                        name="graph_edge_source__ae6465_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=500)),
                (
                    "alias_type",
                    models.CharField(
                        blank=True,
                        help_text="trading_as, former_name, known_as, etc.",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "source_name",
                    models.CharField(
                        help_text="Companies House, Electoral Commission, Parliament Register, etc.",
                        max_length=200,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="graph.entity",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["name"], name="graph_alias_name_d5af84_idx")],
            },
        ),
    ]
