# Generated by Django 6.0.7 on 2026-07-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("company", "Company"),
                    ("person", "Person (public official)"),
                    ("public_body", "Public body / government organization"),
                    ("political_party", "Political party"),
                    (
                        "regulated_entity",
                        "Other EC-regulated entity (members association, third-party campaigner, etc.)",
                    ),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
