# Generated by Django 6.0.7 on 2026-07-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0002_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_name", ""), _negated=True),
                name="edge_source_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.CheckConstraint(
                condition=models.Q(("match_confidence__gte", 0.0), ("match_confidence__lte", 1.0)),
                name="edge_match_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_from__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="edge_valid_to_after_valid_from",
            ),
        ),
    ]
