# Generated by Django 6.0.7 on 2026-07-26 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0003_edge_edge_source_name_not_empty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        help_text="Electoral Commission, Parliament Register, Companies House, DHSC, etc.",
                        max_length=200,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="Source-native ID (e.g. EC donation ref, Parliament interest ID)",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "snapshot_ref",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 content hash of the raw source snapshot",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("match_confidence", models.FloatField(default=1.0)),
                ("match_method", models.CharField(default="identifier", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="edge",
            name="edge_source_name_not_empty",
        ),
        migrations.RemoveConstraint(
            model_name="edge",
            name="edge_match_confidence_range",
        ),
        migrations.AddField(
            model_name="attestation",
            name="derived_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derivations",
                to="graph.attestation",
            ),
        ),
        migrations.AddField(
            model_name="attestation",
            name="edge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attestations",
                to="graph.edge",
            ),
        ),
        migrations.RemoveField(
            model_name="edge",
            name="match_confidence",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="match_method",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="source_name",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="source_reference",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="source_url",
        ),
        migrations.AddIndex(
            model_name="attestation",
            index=models.Index(fields=["source_name"], name="graph_attes_source__b943ff_idx"),
        ),
        migrations.AddIndex(
            model_name="attestation",
            index=models.Index(
                fields=["edge", "source_name"], name="graph_attes_edge_id_fe43c4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attestation",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_name", ""), _negated=True),
                name="attestation_source_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="attestation",
            constraint=models.CheckConstraint(
                condition=models.Q(("match_confidence__gte", 0.0), ("match_confidence__lte", 1.0)),
                name="attestation_match_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="attestation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_reference__isnull", False)),
                fields=("edge", "source_name", "source_reference"),
                name="unique_attestation_per_source_ref",
            ),
        ),
    ]
