# Generated by Django 6.0.7 on 2026-07-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0004_attestation_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="registry_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
