# Generated by Django 6.0.7 on 2026-07-23 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_id", models.CharField(db_index=True, max_length=50)),
                ("tender_id", models.CharField(max_length=200)),
                ("ocid", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("procurement_method", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "procurement_method_details",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("award_criteria", models.CharField(blank=True, max_length=50, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("value_amount_cents", models.BigIntegerField(default=0)),
                ("tender_start", models.DateTimeField(blank=True, null=True)),
                ("tender_end", models.DateTimeField(blank=True, null=True)),
                ("buyer_name", models.CharField(blank=True, max_length=500, null=True)),
                ("buyer_id_scheme", models.CharField(blank=True, max_length=50, null=True)),
                ("buyer_id", models.CharField(blank=True, max_length=200, null=True)),
                ("buyer_country", models.CharField(blank=True, max_length=10, null=True)),
                ("item_count", models.IntegerField(blank=True, null=True)),
                ("raw_json", models.JSONField(default=dict)),
                ("source_url", models.URLField(max_length=1000)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_id", "buyer_name"], name="staging_ten_source__ffcd20_idx"
                    ),
                    models.Index(
                        fields=["procurement_method"], name="staging_ten_procure_89bd66_idx"
                    ),
                ],
                "unique_together": {("source_id", "tender_id")},
            },
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("indicator_id", models.CharField(db_index=True, max_length=50)),
                ("subject_ref", models.CharField(max_length=500)),
                ("as_of", models.DateField()),
                ("explanation", models.TextField()),
                ("evidence_json", models.JSONField(default=list)),
                ("stamp_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("escalated", "Escalated"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "tender_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flags",
                        to="staging.tender",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["indicator_id", "review_status"],
                        name="staging_fla_indicat_94f554_idx",
                    ),
                    models.Index(fields=["as_of"], name="staging_fla_as_of_0f17eb_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_id", models.CharField(db_index=True, max_length=50)),
                ("tender_id", models.CharField(max_length=200)),
                ("bid_id", models.CharField(max_length=200)),
                ("bidder_name", models.CharField(blank=True, max_length=500, null=True)),
                ("bidder_id", models.CharField(blank=True, max_length=200, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("value_amount_cents", models.BigIntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("bid_date", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(default=dict)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tender_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="staging.tender",
                    ),
                ),
            ],
            options={
                "unique_together": {("source_id", "tender_id", "bid_id")},
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_id", models.CharField(db_index=True, max_length=50)),
                ("tender_id", models.CharField(max_length=200)),
                ("award_id", models.CharField(max_length=200)),
                ("supplier_name", models.CharField(blank=True, max_length=500, null=True)),
                ("supplier_id_scheme", models.CharField(blank=True, max_length=50, null=True)),
                ("supplier_id", models.CharField(blank=True, max_length=200, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("value_amount_cents", models.BigIntegerField(default=0)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("award_date", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(default=dict)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tender_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="staging.tender",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_id", "supplier_name"], name="staging_awa_source__e8d318_idx"
                    )
                ],
                "unique_together": {("source_id", "tender_id", "award_id")},
            },
        ),
    ]
