# Generated by Django 6.0.7 on 2026-07-24 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "company_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("company_name", models.CharField(db_index=True, max_length=500)),
                ("company_status", models.CharField(blank=True, max_length=50, null=True)),
                ("incorporation_date", models.DateField(blank=True, null=True)),
                ("accounts_category", models.CharField(blank=True, max_length=100, null=True)),
                ("accounts_last_made_up_date", models.DateField(blank=True, null=True)),
                ("sic_codes", models.TextField(blank=True, null=True)),
                ("registered_address", models.TextField(blank=True, null=True)),
                (
                    "normalised_name",
                    models.CharField(blank=True, db_index=True, max_length=500, null=True),
                ),
                ("bulk_snapshot_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["normalised_name"], name="staging_com_normali_380fd4_idx"),
                    models.Index(fields=["company_name"], name="staging_com_company_89da51_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_id", models.CharField(db_index=True, max_length=50)),
                ("supplier_name", models.CharField(max_length=500)),
                ("supplier_id_scheme", models.CharField(blank=True, max_length=50, null=True)),
                ("supplier_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "company_number",
                    models.CharField(blank=True, db_index=True, max_length=20, null=True),
                ),
                ("match_confidence", models.FloatField(default=0.0)),
                (
                    "match_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("identifier", "Identifier (GB-COH)"),
                            ("exact_name", "Exact name"),
                            ("normalised_name", "Normalised name (deferred)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("normalisation_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions",
                        to="staging.company",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_id", "match_method"], name="staging_sup_source__e6e8da_idx"
                    ),
                    models.Index(fields=["company_number"], name="staging_sup_company_ec56f0_idx"),
                ],
                "unique_together": {("source_id", "supplier_name")},
            },
        ),
    ]
