# Generated by Django 6.0.7 on 2026-07-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staging", "0002_company_supplierresolution"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_id", models.CharField(db_index=True, max_length=50)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("rows_ingested", models.IntegerField(default=0)),
                ("content_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-finished_at"],
                "indexes": [
                    models.Index(
                        fields=["source_id", "-finished_at"], name="staging_ing_source__41352e_idx"
                    ),
                    models.Index(fields=["status"], name="staging_ing_status_e44e7f_idx"),
                ],
            },
        ),
    ]
