# Generated by Django 6.0.7 on 2026-08-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staging", "0004_company_accounts_next_due_company_company_category_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="supplierresolution",
            unique_together={("source_id", "supplier_id")},
        ),
        migrations.AddIndex(
            model_name="supplierresolution",
            index=models.Index(
                fields=["source_id", "supplier_name"], name="staging_sup_source__d0879f_idx"
            ),
        ),
    ]
