# Generated by Django 6.0.7 on 2026-08-14 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staging", "0004_company_accounts_next_due_company_company_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_id", models.CharField(db_index=True, max_length=50)),
                (
                    "company_number",
                    models.CharField(blank=True, db_index=True, max_length=20, null=True),
                ),
                (
                    "match_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("identifier", "Identifier (GB-COH)"),
                            ("exact_name", "Exact name"),
                            ("normalised_name", "Normalised name (deferred)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("match_confidence", models.FloatField(default=0.0)),
                ("normalisation_note", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(auto_now=True)),
                ("ch_snapshot_date", models.DateField(blank=True, null=True)),
                (
                    "award",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution",
                        to="staging.award",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="award_resolutions",
                        to="staging.company",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_id", "match_method"], name="staging_awa_source__05f030_idx"
                    ),
                    models.Index(fields=["company_number"], name="staging_awa_company_4aa695_idx"),
                ],
            },
        ),
    ]
