# Generated by Django 6.0.7 on 2026-08-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staging", "0005_awardresolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="value_kind",
            field=models.CharField(
                choices=[
                    ("per_supplier", "Per-supplier award value"),
                    ("shared_ceiling", "Aggregate ceiling shared across multiple suppliers"),
                ],
                db_index=True,
                default="per_supplier",
                max_length=20,
            ),
        ),
    ]
